<?php

use Hopkins\SlackAgainstHumanity\Models\Card;
use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{
    public function run()
    {
        Card::create(["color" => "white", "text" => "Tweeting."]);
        Card::create(["color" => "white", "text" => "(I am doing Kegels right now.)"]);
        Card::create(["color" => "white", "text" => "2 Girls 1 Cup."]);
        Card::create(["color" => "white", "text" => "50,000 volts straight to the nipples."]);
        Card::create(["color" => "white", "text" => "72 virgins."]);
        Card::create(["color" => "white", "text" => "8 oz. of sweet Mexican black-tar heroin."]);
        Card::create(["color" => "white", "text" => "A bag of magic beans."]);
        Card::create(["color" => "white", "text" => "A balanced breakfast."]);
        Card::create(["color" => "white", "text" => "A ball of earwax, semen, and toenail clippings."]);
        Card::create(["color" => "white", "text" => "A big hoopla about nothing."]);
        Card::create(["color" => "white", "text" => "A bitch slap."]);
        Card::create(["color" => "white", "text" => "A bleached asshole."]);
        Card::create(["color" => "white", "text" => "A Bop It™."]);
        Card::create(["color" => "white", "text" => "A brain tumor."]);
        Card::create(["color" => "white", "text" => "A bucket of fish heads."]);
        Card::create(["color" => "white", "text" => "A can of whoop-ass."]);
        Card::create(["color" => "white", "text" => "A caress of the inner thigh"]);
        Card::create(["color" => "white", "text" => "A cartoon camel enjoying the smooth, refreshing taste of a cigarette."]);
        Card::create(["color" => "white", "text" => "A clandestine butt scratch."]);
        Card::create(["color" => "white", "text" => "A cooler full of organs."]);
        Card::create(["color" => "white", "text" => "A death ray."]);
        Card::create(["color" => "white", "text" => "A defective condom."]);
        Card::create(["color" => "white", "text" => "A disappointing birthday party."]);
        Card::create(["color" => "white", "text" => "A drive-by shooting."]);
        Card::create(["color" => "white", "text" => "A falcon with a cap on its head."]);
        Card::create(["color" => "white", "text" => "A fetus."]);
        Card::create(["color" => "white", "text" => "A Fleshlight."]);
        Card::create(["color" => "white", "text" => "A foul mouth."]);
        Card::create(["color" => "white", "text" => "A gassy antelope."]);
        Card::create(["color" => "white", "text" => "A gentle caress of the inner thigh."]);
        Card::create(["color" => "white", "text" => "A good sniff."]);
        Card::create(["color" => "white", "text" => "A grande sugar-free iced soy caramel macchiato."]);
        Card::create(["color" => "white", "text" => "A Gypsy curse."]);
        Card::create(["color" => "white", "text" => "A homoerotic volleyball montage."]);
        Card::create(["color" => "white", "text" => "A hot mess."]);
        Card::create(["color" => "white", "text" => "A LAN party."]);
        Card::create(["color" => "white", "text" => "A lifetime of sadness."]);
        Card::create(["color" => "white", "text" => "A live studio audience."]);
        Card::create(["color" => "white", "text" => "A look-see."]);
        Card::create(["color" => "white", "text" => "A man on the brink of orgasm."]);
        Card::create(["color" => "white", "text" => "A mating display."]);
        Card::create(["color" => "white", "text" => "A micropenis."]);
        Card::create(["color" => "white", "text" => "A micropig wearing a tiny raincoat and booties."]);
        Card::create(["color" => "white", "text" => "A middle-aged man on roller skates."]);
        Card::create(["color" => "white", "text" => "A mime having a stroke."]);
        Card::create(["color" => "white", "text" => "A moment of silence."]);
        Card::create(["color" => "white", "text" => "A monkey smoking a cigar."]);
        Card::create(["color" => "white", "text" => "A mopey zoo lion."]);
        Card::create(["color" => "white", "text" => "A murder most foul."]);
        Card::create(["color" => "white", "text" => "A neglected Tamagotchi™."]);
        Card::create(["color" => "white", "text" => "A pyramid of severed heads."]);
        Card::create(["color" => "white", "text" => "A really cool hat."]);
        Card::create(["color" => "white", "text" => "A robust mongoloid."]);
        Card::create(["color" => "white", "text" => "A sad handjob."]);
        Card::create(["color" => "white", "text" => "A salty surprise."]);
        Card::create(["color" => "white", "text" => "A sassy black woman."]);
        Card::create(["color" => "white", "text" => "A sausage festival."]);
        Card::create(["color" => "white", "text" => "A saxophone solo."]);
        Card::create(["color" => "white", "text" => "A sea of troubles."]);
        Card::create(["color" => "white", "text" => "A snapping turtle biting the tip of your penis."]);
        Card::create(["color" => "white", "text" => "A spastic nerd."]);
        Card::create(["color" => "white", "text" => "A stray pube."]);
        Card::create(["color" => "white", "text" => "A subscription to Men's Fitness."]);
        Card::create(["color" => "white", "text" => "A Super Soaker™ full of cat pee."]);
        Card::create(["color" => "white", "text" => "A thermonuclear detonation."]);
        Card::create(["color" => "white", "text" => "A time travel paradox."]);
        Card::create(["color" => "white", "text" => "A tiny horse."]);
        Card::create(["color" => "white", "text" => "A tribe of warrior women."]);
        Card::create(["color" => "white", "text" => "A vajazzled vagina."]);
        Card::create(["color" => "white", "text" => "A wheelchair death race."]);
        Card::create(["color" => "white", "text" => "A windmill full of corpses."]);
        Card::create(["color" => "white", "text" => "A wisecracking terrorist."]);
        Card::create(["color" => "white", "text" => "A zesty breakfast burrito."]);
        Card::create(["color" => "white", "text" => "Aaron Burr."]);
        Card::create(["color" => "white", "text" => "Abstinence."]);
        Card::create(["color" => "white", "text" => "Accidentally slipping yourself a roofie."]);
        Card::create(["color" => "white", "text" => "Active listening."]);
        Card::create(["color" => "white", "text" => "Actually taking candy from a baby."]);
        Card::create(["color" => "white", "text" => "Adderall™."]);
        Card::create(["color" => "white", "text" => "Adult Friendfinder."]);
        Card::create(["color" => "white", "text" => "Advice from a wise, old black man."]);
        Card::create(["color" => "white", "text" => "African children"]);
        Card::create(["color" => "white", "text" => "Agriculture."]);
        Card::create(["color" => "white", "text" => "AIDS."]);
        Card::create(["color" => "white", "text" => "Alcoholism."]);
        Card::create(["color" => "white", "text" => "All-you-can-eat shrimp for $4.99."]);
        Card::create(["color" => "white", "text" => "Altar boys."]);
        Card::create(["color" => "white", "text" => "America."]);
        Card::create(["color" => "white", "text" => "American Gladiators."]);
        Card::create(["color" => "white", "text" => "Amputees."]);
        Card::create(["color" => "white", "text" => "An asymmetric boob job."]);
        Card::create(["color" => "white", "text" => "An endless stream of diarrhea."]);
        Card::create(["color" => "white", "text" => "An erection that lasts longer than four hours."]);
        Card::create(["color" => "white", "text" => "An honest cop with nothing left to lose."]);
        Card::create(["color" => "white", "text" => "An icepick labotomy."]);
        Card::create(["color" => "white", "text" => "An M. Night Shyamalan plot twist."]);
        Card::create(["color" => "white", "text" => "An M16 assault rifle."]);
        Card::create(["color" => "white", "text" => "An Oedipus complex."]);
        Card::create(["color" => "white", "text" => "An oversized lollipop."]);
        Card::create(["color" => "white", "text" => "An ugly face."]);
        Card::create(["color" => "white", "text" => "An uppercut."]);
        Card::create(["color" => "white", "text" => "Anal beads."]);
        Card::create(["color" => "white", "text" => "Another goddamn vampire movie."]);
        Card::create(["color" => "white", "text" => "Arnold Schwarzenegger."]);
        Card::create(["color" => "white", "text" => "Asians who aren't good at math."]);
        Card::create(["color" => "white", "text" => "Assless chaps."]);
        Card::create(["color" => "white", "text" => "Attitude."]);
        Card::create(["color" => "white", "text" => "Auschwitz."]);
        Card::create(["color" => "white", "text" => "Authentic Mexican cuisine."]);
        Card::create(["color" => "white", "text" => "Autocannibalism."]);
        Card::create(["color" => "white", "text" => "AXE Body Spray."]);
        Card::create(["color" => "white", "text" => "Balls."]);
        Card::create(["color" => "white", "text" => "Bananas in Pajamas."]);
        Card::create(["color" => "white", "text" => "Barack Obama."]);
        Card::create(["color" => "white", "text" => "BATMAN!!!"]);
        Card::create(["color" => "white", "text" => "Battlefield amputations."]);
        Card::create(["color" => "white", "text" => "Becoming a blueberry."]);
        Card::create(["color" => "white", "text" => "Bees?"]);
        Card::create(["color" => "white", "text" => "Being a dick to children."]);
        Card::create(["color" => "white", "text" => "Being a motherfucking sorcerer."]);
        Card::create(["color" => "white", "text" => "Being fabulous."]);
        Card::create(["color" => "white", "text" => "Being fat and stupid."]);
        Card::create(["color" => "white", "text" => "Being marginalized."]);
        Card::create(["color" => "white", "text" => "Being on fire."]);
        Card::create(["color" => "white", "text" => "Being rich."]);
        Card::create(["color" => "white", "text" => "Bestiality."]);
        Card::create(["color" => "white", "text" => "Bill Nye the Science Guy."]);
        Card::create(["color" => "white", "text" => "Bingeing and purging."]);
        Card::create(["color" => "white", "text" => "Bio-engineered assault turtles with acid breath."]);
        Card::create(["color" => "white", "text" => "Bitches."]);
        Card::create(["color" => "white", "text" => "Black people."]);
        Card::create(["color" => "white", "text" => "Bling."]);
        Card::create(["color" => "white", "text" => "Bond, James Bond."]);
        Card::create(["color" => "white", "text" => "Bono."]);
        Card::create(["color" => "white", "text" => "Booby-trapping the house to foil burglars."]);
        Card::create(["color" => "white", "text" => "Boogers."]);
        Card::create(["color" => "white", "text" => "Breaking out into song and dance."]);
        Card::create(["color" => "white", "text" => "Britney Spears at 55."]);
        Card::create(["color" => "white", "text" => "Brown people."]);
        Card::create(["color" => "white", "text" => "Canned tuna with extra dolphin."]);
        Card::create(["color" => "white", "text" => "Capturing Newt Gingrich and forcing him to dance in a monkey suit."]);
        Card::create(["color" => "white", "text" => "Cards Against Humanity."]);
        Card::create(["color" => "white", "text" => "Catapults."]);
        Card::create(["color" => "white", "text" => "Centaurs."]);
        Card::create(["color" => "white", "text" => "Chainsaws for hands."]);
        Card::create(["color" => "white", "text" => "Charisma."]);
        Card::create(["color" => "white", "text" => "Cheating in the Special Olympics."]);
        Card::create(["color" => "white", "text" => "Child abuse."]);
        Card::create(["color" => "white", "text" => "Child beauty pageants."]);
        Card::create(["color" => "white", "text" => "Children on leashes."]);
        Card::create(["color" => "white", "text" => "Chivalry."]);
        Card::create(["color" => "white", "text" => "Christopher Walken."]);
        Card::create(["color" => "white", "text" => "Chunks of dead hitchhiker."]);
        Card::create(["color" => "white", "text" => "Chunks of dead prostitute."]);
        Card::create(["color" => "white", "text" => "Chutzpah."]);
        Card::create(["color" => "white", "text" => "Civilian casualties."]);
        Card::create(["color" => "white", "text" => "Classist undertones."]);
        Card::create(["color" => "white", "text" => "Coat hanger abortions."]);
        Card::create(["color" => "white", "text" => "Cockfights."]);
        Card::create(["color" => "white", "text" => "College."]);
        Card::create(["color" => "white", "text" => "Concealing a boner."]);
        Card::create(["color" => "white", "text" => "Consensual sex."]);
        Card::create(["color" => "white", "text" => "Consultants."]);
        Card::create(["color" => "white", "text" => "Cookie Monster devouring the Eucharist wafers."]);
        Card::create(["color" => "white", "text" => "Copping a feel."]);
        Card::create(["color" => "white", "text" => "Count Chocula."]);
        Card::create(["color" => "white", "text" => "Court-ordered rehab."]);
        Card::create(["color" => "white", "text" => "Creed."]);
        Card::create(["color" => "white", "text" => "Crippling debt."]);
        Card::create(["color" => "white", "text" => "Crucifixion."]);
        Card::create(["color" => "white", "text" => "Crumbs all over the god damn carpet."]);
        Card::create(["color" => "white", "text" => "Crumpets with the Queen."]);
        Card::create(["color" => "white", "text" => "Crystal meth."]);
        Card::create(["color" => "white", "text" => "Cuddling."]);
        Card::create(["color" => "white", "text" => "Customer service representatives."]);
        Card::create(["color" => "white", "text" => "Cybernetic enhancements."]);
        Card::create(["color" => "white", "text" => "Daddy issues."]);
        Card::create(["color" => "white", "text" => "Daniel Radcliffe's delicious asshole."]);
        Card::create(["color" => "white", "text" => "Dark and mysterious forces beyond our control."]);
        Card::create(["color" => "white", "text" => "Darth Vader."]);
        Card::create(["color" => "white", "text" => "Date rape."]);
        Card::create(["color" => "white", "text" => "Dave Matthews Band."]);
        Card::create(["color" => "white", "text" => "David Bowie flying in on a tiger made of lightning. "]);
        Card::create(["color" => "white", "text" => "Dead babies."]);
        Card::create(["color" => "white", "text" => "Dead parents."]);
        Card::create(["color" => "white", "text" => "Dental dams."]);
        Card::create(["color" => "white", "text" => "Destroying the evidence."]);
        Card::create(["color" => "white", "text" => "Dick Cheney"]);
        Card::create(["color" => "white", "text" => "Dick fingers."]);
        Card::create(["color" => "white", "text" => "Doin' it in the butt."]);
        Card::create(["color" => "white", "text" => "Doing the right thing."]);
        Card::create(["color" => "white", "text" => "Domino's™ Oreo™ Dessert Pizza."]);
        Card::create(["color" => "white", "text" => "Donald Trump."]);
        Card::create(["color" => "white", "text" => "Douchebags on their iPhones."]);
        Card::create(["color" => "white", "text" => "Dr. Martin Luther King, Jr."]);
        Card::create(["color" => "white", "text" => "Drinking alone."]);
        Card::create(["color" => "white", "text" => "Dropping a chandelier on your enemies and riding the rope up."]);
        Card::create(["color" => "white", "text" => "Drum circles."]);
        Card::create(["color" => "white", "text" => "Dry heaving."]);
        Card::create(["color" => "white", "text" => "Dwarf tossing."]);
        Card::create(["color" => "white", "text" => "Dying of dysentery."]);
        Card::create(["color" => "white", "text" => "Dying."]);
        Card::create(["color" => "white", "text" => "Eastern European Turbo-Folk music."]);
        Card::create(["color" => "white", "text" => "Eating all of the cookies before the AIDS bake-sale."]);
        Card::create(["color" => "white", "text" => "Eating the last known bison."]);
        Card::create(["color" => "white", "text" => "Eating too much of a lamp."]);
        Card::create(["color" => "white", "text" => "Edible underpants."]);
        Card::create(["color" => "white", "text" => "Elderly Japanese men."]);
        Card::create(["color" => "white", "text" => "Electricity."]);
        Card::create(["color" => "white", "text" => "Embryonic stem cells."]);
        Card::create(["color" => "white", "text" => "Emma Watson."]);
        Card::create(["color" => "white", "text" => "Emotions."]);
        Card::create(["color" => "white", "text" => "Erectile dysfunction."]);
        Card::create(["color" => "white", "text" => "Establishing Dominance."]);
        Card::create(["color" => "white", "text" => "Estrogen."]);
        Card::create(["color" => "white", "text" => "Ethnic cleansing."]);
        Card::create(["color" => "white", "text" => "Eugenics."]);
        Card::create(["color" => "white", "text" => "Euphoria™ by Calvin Klein."]);
        Card::create(["color" => "white", "text" => "Exactly what you'd expect."]);
        Card::create(["color" => "white", "text" => "Exchanging pleasantries."]);
        Card::create(["color" => "white", "text" => "Existentialists."]);
        Card::create(["color" => "white", "text" => "Expecting a burp and vomiting on the floor."]);
        Card::create(["color" => "white", "text" => "Explosions."]);
        Card::create(["color" => "white", "text" => "Extremely tight pants."]);
        Card::create(["color" => "white", "text" => "Faith healing."]);
        Card::create(["color" => "white", "text" => "FALCON PUNCH!!!"]);
        Card::create(["color" => "white", "text" => "Famine."]);
        Card::create(["color" => "white", "text" => "Fancy Feast®."]);
        Card::create(["color" => "white", "text" => "Farting and walking away."]);
        Card::create(["color" => "white", "text" => "Farting into your petticoats and wafting it at Lord Gregory."]);
        Card::create(["color" => "white", "text" => "Fear itself."]);
        Card::create(["color" => "white", "text" => "Feeding Rosie O'Donnell."]);
        Card::create(["color" => "white", "text" => "Fiery poops."]);
        Card::create(["color" => "white", "text" => "Figgy pudding."]);
        Card::create(["color" => "white", "text" => "Filling Sean Hannity with helium and watching him float away."]);
        Card::create(["color" => "white", "text" => "Finger painting."]);
        Card::create(["color" => "white", "text" => "Fingering."]);
        Card::create(["color" => "white", "text" => "Firing a rifle into the air while balls deep in a squealing hog."]);
        Card::create(["color" => "white", "text" => "Five-Dollar Footlongs™."]);
        Card::create(["color" => "white", "text" => "Flash flooding."]);
        Card::create(["color" => "white", "text" => "Flavored condoms."]);
        Card::create(["color" => "white", "text" => "Flesh-eating bacteria."]);
        Card::create(["color" => "white", "text" => "Flightless birds."]);
        Card::create(["color" => "white", "text" => "Flying sex snakes."]);
        Card::create(["color" => "white", "text" => "Foreskin."]);
        Card::create(["color" => "white", "text" => "Forgetting the Alamo."]);
        Card::create(["color" => "white", "text" => "Former President George W. Bush."]);
        Card::create(["color" => "white", "text" => "Four Loko."]);
        Card::create(["color" => "white", "text" => "Free samples."]);
        Card::create(["color" => "white", "text" => "Friction."]);
        Card::create(["color" => "white", "text" => "Friendly fire."]);
        Card::create(["color" => "white", "text" => "Friends who eat all the snacks."]);
        Card::create(["color" => "white", "text" => "Friends with benefits."]);
        Card::create(["color" => "white", "text" => "Frolicking."]);
        Card::create(["color" => "white", "text" => "Front butt."]);
        Card::create(["color" => "white", "text" => "Full frontal nudity."]);
        Card::create(["color" => "white", "text" => "Funky fresh rhymes."]);
        Card::create(["color" => "white", "text" => "Gandhi."]);
        Card::create(["color" => "white", "text" => "Garth Brooks."]);
        Card::create(["color" => "white", "text" => "Gary Coleman."]);
        Card::create(["color" => "white", "text" => "Geese."]);
        Card::create(["color" => "white", "text" => "Genghis Khan."]);
        Card::create(["color" => "white", "text" => "Genital piercings."]);
        Card::create(["color" => "white", "text" => "Genuine human connection."]);
        Card::create(["color" => "white", "text" => "German dungeon porn."]);
        Card::create(["color" => "white", "text" => "Getting drunk on mouthwash."]);
        Card::create(["color" => "white", "text" => "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."]);
        Card::create(["color" => "white", "text" => "Getting naked and watching Nickelodeon."]);
        Card::create(["color" => "white", "text" => "Getting really high."]);
        Card::create(["color" => "white", "text" => "Getting so angry that you pop a boner."]);
        Card::create(["color" => "white", "text" => "Ghosts."]);
        Card::create(["color" => "white", "text" => "Girls who shouldn't go wild."]);
        Card::create(["color" => "white", "text" => "Giving 110%"]);
        Card::create(["color" => "white", "text" => "Giving birth to the Antichrist."]);
        Card::create(["color" => "white", "text" => "Glenn Beck being harried by a swarm of buzzards."]);
        Card::create(["color" => "white", "text" => "Glenn Beck catching his scrotum on a curtain hook."]);
        Card::create(["color" => "white", "text" => "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts."]);
        Card::create(["color" => "white", "text" => "Glenn Beck."]);
        Card::create(["color" => "white", "text" => "Global warming."]);
        Card::create(["color" => "white", "text" => "Gloryholes."]);
        Card::create(["color" => "white", "text" => "Goats eating cans."]);
        Card::create(["color" => "white", "text" => "Goats eating coins."]);
        Card::create(["color" => "white", "text" => "Goblins."]);
        Card::create(["color" => "white", "text" => "God."]);
        Card::create(["color" => "white", "text" => "GoGurt®."]);
        Card::create(["color" => "white", "text" => "Golden showers."]);
        Card::create(["color" => "white", "text" => "Grandma."]);
        Card::create(["color" => "white", "text" => "Grave robbing."]);
        Card::create(["color" => "white", "text" => "Growing a pair."]);
        Card::create(["color" => "white", "text" => "Guys who don't call."]);
        Card::create(["color" => "white", "text" => "Half-assed foreplay."]);
        Card::create(["color" => "white", "text" => "Harry Potter erotica."]);
        Card::create(["color" => "white", "text" => "Have some more kugel."]);
        Card::create(["color" => "white", "text" => "Having anuses for eyes."]);
        Card::create(["color" => "white", "text" => "Heartwarming orphans."]);
        Card::create(["color" => "white", "text" => "Heath Ledger."]);
        Card::create(["color" => "white", "text" => "Helplessly giggling at the mention of Hutus and Tutsis."]);
        Card::create(["color" => "white", "text" => "Her Majesty, Queen Elizabeth II."]);
        Card::create(["color" => "white", "text" => "Her Royal Highness, Queen Elizabeth II."]);
        Card::create(["color" => "white", "text" => "Heteronormativity."]);
        Card::create(["color" => "white", "text" => "Hip hop jewels"]);
        Card::create(["color" => "white", "text" => "Historically black colleges."]);
        Card::create(["color" => "white", "text" => "Holding down a child and farting all over him."]);
        Card::create(["color" => "white", "text" => "Home video of Oprah sobbing into a Lean Cuisine®."]);
        Card::create(["color" => "white", "text" => "Homeless people."]);
        Card::create(["color" => "white", "text" => "Hope."]);
        Card::create(["color" => "white", "text" => "Hormone injections."]);
        Card::create(["color" => "white", "text" => "Horrifying laser hair removal accidents."]);
        Card::create(["color" => "white", "text" => "Horse meat."]);
        Card::create(["color" => "white", "text" => "Hospice care."]);
        Card::create(["color" => "white", "text" => "Hot cheese."]);
        Card::create(["color" => "white", "text" => "Hot people."]);
        Card::create(["color" => "white", "text" => "Hot Pockets®."]);
        Card::create(["color" => "white", "text" => "Hulk Hogan."]);
        Card::create(["color" => "white", "text" => "Hunting 'accidents'."]);
        Card::create(["color" => "white", "text" => "Hurricane Katrina."]);
        Card::create(["color" => "white", "text" => "I'm friends with your dad on Facebook."]);
        Card::create(["color" => "white", "text" => "Impotence."]);
        Card::create(["color" => "white", "text" => "Improvised explosive devices."]);
        Card::create(["color" => "white", "text" => "Inappropriate yelling."]);
        Card::create(["color" => "white", "text" => "Inappropriate yodeling."]);
        Card::create(["color" => "white", "text" => "Incest."]);
        Card::create(["color" => "white", "text" => "Inserting a Mason jar into my anus."]);
        Card::create(["color" => "white", "text" => "Intelligent design."]);
        Card::create(["color" => "white", "text" => "Invading Poland."]);
        Card::create(["color" => "white", "text" => "Irritable Bowel Syndrome."]);
        Card::create(["color" => "white", "text" => "Italians."]);
        Card::create(["color" => "white", "text" => "Jerking off into a pool of children's tears."]);
        Card::create(["color" => "white", "text" => "Jew-fros."]);
        Card::create(["color" => "white", "text" => "Jewish fraternities."]);
        Card::create(["color" => "white", "text" => "Jibber-jabber."]);
        Card::create(["color" => "white", "text" => "Jobs."]);
        Card::create(["color" => "white", "text" => "Joe Biden."]);
        Card::create(["color" => "white", "text" => "John Wilkes Booth"]);
        Card::create(["color" => "white", "text" => "Judge Judy."]);
        Card::create(["color" => "white", "text" => "Justin Bieber."]);
        Card::create(["color" => "white", "text" => "Kamikaze pilots."]);
        Card::create(["color" => "white", "text" => "Kanye West."]);
        Card::create(["color" => "white", "text" => "Keanu Reeves."]);
        Card::create(["color" => "white", "text" => "Keeping Christ in Christmas."]);
        Card::create(["color" => "white", "text" => "Keg stands."]);
        Card::create(["color" => "white", "text" => "Kibbles n' Bits."]);
        Card::create(["color" => "white", "text" => "Kids with ass cancer."]);
        Card::create(["color" => "white", "text" => "Kim Jong-il."]);
        Card::create(["color" => "white", "text" => "Lactation."]);
        Card::create(["color" => "white", "text" => "Lady Gaga."]);
        Card::create(["color" => "white", "text" => "Lance Armstrong's missing testicle."]);
        Card::create(["color" => "white", "text" => "Land mines."]);
        Card::create(["color" => "white", "text" => "Laying an egg."]);
        Card::create(["color" => "white", "text" => "Leaving an awkward voicemail."]);
        Card::create(["color" => "white", "text" => "Leprosy."]);
        Card::create(["color" => "white", "text" => "Letting yourself go."]);
        Card::create(["color" => "white", "text" => "Licking things to claim them as your own."]);
        Card::create(["color" => "white", "text" => "Lockjaw."]);
        Card::create(["color" => "white", "text" => "Loose lips."]);
        Card::create(["color" => "white", "text" => "Lumberjack fantasies."]);
        Card::create(["color" => "white", "text" => "Lunchables™."]);
        Card::create(["color" => "white", "text" => "Mad cow disease."]);
        Card::create(["color" => "white", "text" => "Magnets."]);
        Card::create(["color" => "white", "text" => "Making a pouty face."]);
        Card::create(["color" => "white", "text" => "Making sex at her."]);
        Card::create(["color" => "white", "text" => "Man meat."]);
        Card::create(["color" => "white", "text" => "Marky Mark and the Funky Bunch."]);
        Card::create(["color" => "white", "text" => "Martha Stewart."]);
        Card::create(["color" => "white", "text" => "Masturbation."]);
        Card::create(["color" => "white", "text" => "Mathletes."]);
        Card::create(["color" => "white", "text" => "Me time."]);
        Card::create(["color" => "white", "text" => "MechaHitler."]);
        Card::create(["color" => "white", "text" => "Men."]);
        Card::create(["color" => "white", "text" => "Menstrual rage."]);
        Card::create(["color" => "white", "text" => "Menstruation."]);
        Card::create(["color" => "white", "text" => "Michael Jackson."]);
        Card::create(["color" => "white", "text" => "Michelle Obama's arms."]);
        Card::create(["color" => "white", "text" => "Miley Cyrus at 55."]);
        Card::create(["color" => "white", "text" => "Mistaking a retarded person for someone who's merely deaf."]);
        Card::create(["color" => "white", "text" => "Morgan Freeman's voice."]);
        Card::create(["color" => "white", "text" => "Mountain Dew Code Red."]);
        Card::create(["color" => "white", "text" => "Mouth herpes."]);
        Card::create(["color" => "white", "text" => "Mr. Clean, right behind you."]);
        Card::create(["color" => "white", "text" => "Mr. Snuffleupagus."]);
        Card::create(["color" => "white", "text" => "Muhammad (Praise Be Unto Him)."]);
        Card::create(["color" => "white", "text" => "Multiple stab wounds."]);
        Card::create(["color" => "white", "text" => "Mutually-assured destruction."]);
        Card::create(["color" => "white", "text" => "Muzzy."]);
        Card::create(["color" => "white", "text" => "My black ass."]);
        Card::create(["color" => "white", "text" => "My collection of high-tech sex toys."]);
        Card::create(["color" => "white", "text" => "My ex-wife."]);
        Card::create(["color" => "white", "text" => "My genitals."]);
        Card::create(["color" => "white", "text" => "My humps."]);
        Card::create(["color" => "white", "text" => "My inner demons."]);
        Card::create(["color" => "white", "text" => "My relationship status."]);
        Card::create(["color" => "white", "text" => "My sex life."]);
        Card::create(["color" => "white", "text" => "My soul."]);
        Card::create(["color" => "white", "text" => "My vagina."]);
        Card::create(["color" => "white", "text" => "Natalie Portman."]);
        Card::create(["color" => "white", "text" => "Natural male enhancement."]);
        Card::create(["color" => "white", "text" => "Natural selection."]);
        Card::create(["color" => "white", "text" => "Nazis."]);
        Card::create(["color" => "white", "text" => "Necrophilia."]);
        Card::create(["color" => "white", "text" => "New Age music."]);
        Card::create(["color" => "white", "text" => "Nickelback."]);
        Card::create(["color" => "white", "text" => "Nicolas Cage."]);
        Card::create(["color" => "white", "text" => "Nip slips."]);
        Card::create(["color" => "white", "text" => "Nipple blades."]);
        Card::create(["color" => "white", "text" => "Nocturnal emissions."]);
        Card::create(["color" => "white", "text" => "Not giving a shit about the Third World."]);
        Card::create(["color" => "white", "text" => "Not reciprocating oral sex."]);
        Card::create(["color" => "white", "text" => "Not wearing pants."]);
        Card::create(["color" => "white", "text" => "Obesity."]);
        Card::create(["color" => "white", "text" => "Object permanence."]);
        Card::create(["color" => "white", "text" => "Old-people smell."]);
        Card::create(["color" => "white", "text" => "One trillion dollars."]);
        Card::create(["color" => "white", "text" => "Oompa-Loompas."]);
        Card::create(["color" => "white", "text" => "Opposable thumbs."]);
        Card::create(["color" => "white", "text" => "Our first chimpanzee President."]);
        Card::create(["color" => "white", "text" => "Overcompensation."]);
        Card::create(["color" => "white", "text" => "Oversized lollipops."]);
        Card::create(["color" => "white", "text" => "Pabst Blue Ribbon."]);
        Card::create(["color" => "white", "text" => "Pac-Man uncontrollably guzzling cum."]);
        Card::create(["color" => "white", "text" => "Panda sex."]);
        Card::create(["color" => "white", "text" => "Paris Hilton."]);
        Card::create(["color" => "white", "text" => "Parting the Red Sea."]);
        Card::create(["color" => "white", "text" => "Party poopers."]);
        Card::create(["color" => "white", "text" => "Passable transvestites."]);
        Card::create(["color" => "white", "text" => "Passing a kidney stone."]);
        Card::create(["color" => "white", "text" => "Passive-aggression."]);
        Card::create(["color" => "white", "text" => "Passive-aggressive Post-it notes."]);
        Card::create(["color" => "white", "text" => "PCP."]);
        Card::create(["color" => "white", "text" => "Peanut Butter Jelly Time."]);
        Card::create(["color" => "white", "text" => "Pedophiles."]);
        Card::create(["color" => "white", "text" => "Peeing a little bit."]);
        Card::create(["color" => "white", "text" => "Penis breath."]);
        Card::create(["color" => "white", "text" => "Penis envy."]);
        Card::create(["color" => "white", "text" => "People who smell their own socks."]);
        Card::create(["color" => "white", "text" => "Picking up girls at the abortion clinic."]);
        Card::create(["color" => "white", "text" => "Pictures of boobs."]);
        Card::create(["color" => "white", "text" => "Pixelated bukkake."]);
        Card::create(["color" => "white", "text" => "Police Brutality."]);
        Card::create(["color" => "white", "text" => "Pooping back and forth. Forever."]);
        Card::create(["color" => "white", "text" => "Pooping in the soup."]);
        Card::create(["color" => "white", "text" => "Poopy diapers."]);
        Card::create(["color" => "white", "text" => "Poor life choices."]);
        Card::create(["color" => "white", "text" => "Poor people."]);
        Card::create(["color" => "white", "text" => "Poorly-timed Holocaust jokes."]);
        Card::create(["color" => "white", "text" => "Popped collars."]);
        Card::create(["color" => "white", "text" => "Porn stars."]);
        Card::create(["color" => "white", "text" => "Powerful thighs."]);
        Card::create(["color" => "white", "text" => "Prancing."]);
        Card::create(["color" => "white", "text" => "Praying the gay away."]);
        Card::create(["color" => "white", "text" => "Preteens."]);
        Card::create(["color" => "white", "text" => "Pretending to care."]);
        Card::create(["color" => "white", "text" => "Prosti-tots."]);
        Card::create(["color" => "white", "text" => "Pterodactyl eggs."]);
        Card::create(["color" => "white", "text" => "Puberty."]);
        Card::create(["color" => "white", "text" => "Public ridicule."]);
        Card::create(["color" => "white", "text" => "Pulling out."]);
        Card::create(["color" => "white", "text" => "Puppies!"]);
        Card::create(["color" => "white", "text" => "Queefing."]);
        Card::create(["color" => "white", "text" => "Racially-biased SAT questions."]);
        Card::create(["color" => "white", "text" => "Racism."]);
        Card::create(["color" => "white", "text" => "Raping and pillaging."]);
        Card::create(["color" => "white", "text" => "Raptor attacks."]);
        Card::create(["color" => "white", "text" => "Re-gifting."]);
        Card::create(["color" => "white", "text" => "Rehab."]);
        Card::create(["color" => "white", "text" => "Repression."]);
        Card::create(["color" => "white", "text" => "Republicans."]);
        Card::create(["color" => "white", "text" => "Riding off into the sunset."]);
        Card::create(["color" => "white", "text" => "Ring Pops™."]);
        Card::create(["color" => "white", "text" => "Rip Torn dropkicking anti-Semitic lesbians."]);
        Card::create(["color" => "white", "text" => "Road head."]);
        Card::create(["color" => "white", "text" => "Robbing a sperm bank."]);
        Card::create(["color" => "white", "text" => "Robert Downey, Jr."]);
        Card::create(["color" => "white", "text" => "RoboCop."]);
        Card::create(["color" => "white", "text" => "Ronald Reagan."]);
        Card::create(["color" => "white", "text" => "Roofies."]);
        Card::create(["color" => "white", "text" => "Running out of semen."]);
        Card::create(["color" => "white", "text" => "Rush Limbaugh's soft, shitty body."]);
        Card::create(["color" => "white", "text" => "Same-sex ice dancing."]);
        Card::create(["color" => "white", "text" => "Sarah Palin."]);
        Card::create(["color" => "white", "text" => "Saxophone solos."]);
        Card::create(["color" => "white", "text" => "Saying 'I love you.'"]);
        Card::create(["color" => "white", "text" => "Scalping."]);
        Card::create(["color" => "white", "text" => "Science."]);
        Card::create(["color" => "white", "text" => "Scientology."]);
        Card::create(["color" => "white", "text" => "Scrubbing under the folds."]);
        Card::create(["color" => "white", "text" => "Sean Connery."]);
        Card::create(["color" => "white", "text" => "Sean Penn."]);
        Card::create(["color" => "white", "text" => "Seduction."]);
        Card::create(["color" => "white", "text" => "Seeing Grandma naked."]);
        Card::create(["color" => "white", "text" => "Self-loathing."]);
        Card::create(["color" => "white", "text" => "Seppuku."]);
        Card::create(["color" => "white", "text" => "Serfdom."]);
        Card::create(["color" => "white", "text" => "Sex with Patrick Stewart."]);
        Card::create(["color" => "white", "text" => "Sexting."]);
        Card::create(["color" => "white", "text" => "Sexual peeing."]);
        Card::create(["color" => "white", "text" => "Sexual tension."]);
        Card::create(["color" => "white", "text" => "Sexy pillow fights."]);
        Card::create(["color" => "white", "text" => "Shapeshifters."]);
        Card::create(["color" => "white", "text" => "Shaquille O'Neal's acting career."]);
        Card::create(["color" => "white", "text" => "Sharing needles."]);
        Card::create(["color" => "white", "text" => "Shiny objects."]);
        Card::create(["color" => "white", "text" => "Shorties and blunts."]);
        Card::create(["color" => "white", "text" => "Showing up to an orgy for the food."]);
        Card::create(["color" => "white", "text" => "Silence."]);
        Card::create(["color" => "white", "text" => "Sipping artificial popcorn butter."]);
        Card::create(["color" => "white", "text" => "Skeletor."]);
        Card::create(["color" => "white", "text" => "Smallpox blankets."]);
        Card::create(["color" => "white", "text" => "Smegma."]);
        Card::create(["color" => "white", "text" => "Sniffing glue."]);
        Card::create(["color" => "white", "text" => "Sobbing into a Hungry-Man™ Frozen Dinner"]);
        Card::create(["color" => "white", "text" => "Soiling oneself."]);
        Card::create(["color" => "white", "text" => "Some god-damn peace and quiet."]);
        Card::create(["color" => "white", "text" => "Soup that is too hot."]);
        Card::create(["color" => "white", "text" => "Spectacular abs."]);
        Card::create(["color" => "white", "text" => "Sperm whales."]);
        Card::create(["color" => "white", "text" => "Spontaneous human combustion."]);
        Card::create(["color" => "white", "text" => "Stalin."]);
        Card::create(["color" => "white", "text" => "Stephen Hawking talking dirty."]);
        Card::create(["color" => "white", "text" => "Steve Irwin."]);
        Card::create(["color" => "white", "text" => "Stifling a giggle at the mention of Hutus and Tutsis."]);
        Card::create(["color" => "white", "text" => "Stormtroopers."]);
        Card::create(["color" => "white", "text" => "Stranger danger."]);
        Card::create(["color" => "white", "text" => "Strong female characters."]);
        Card::create(["color" => "white", "text" => "Stunt doubles."]);
        Card::create(["color" => "white", "text" => "Substitute teachers."]);
        Card::create(["color" => "white", "text" => "Sucking some dicks to not get drafted."]);
        Card::create(["color" => "white", "text" => "Sunshine and rainbows."]);
        Card::create(["color" => "white", "text" => "Surprise sex!"]);
        Card::create(["color" => "white", "text" => "Swag."]);
        Card::create(["color" => "white", "text" => "Sweet, sweet vengeance."]);
        Card::create(["color" => "white", "text" => "Switching to Geico®."]);
        Card::create(["color" => "white", "text" => "Swooping."]);
        Card::create(["color" => "white", "text" => "Synergistic management solutions."]);
        Card::create(["color" => "white", "text" => "Take-backsies."]);
        Card::create(["color" => "white", "text" => "Taking off your shirt."]);
        Card::create(["color" => "white", "text" => "Tangled Slinkys."]);
        Card::create(["color" => "white", "text" => "Tasteful sideboob."]);
        Card::create(["color" => "white", "text" => "Teaching a robot to love."]);
        Card::create(["color" => "white", "text" => "Team-building exercises."]);
        Card::create(["color" => "white", "text" => "Teenage pregnancy."]);
        Card::create(["color" => "white", "text" => "Tentacle porn."]);
        Card::create(["color" => "white", "text" => "Testicular torsion."]);
        Card::create(["color" => "white", "text" => "That one gay Teletubby."]);
        Card::create(["color" => "white", "text" => "That thing that electrocutes your abs."]);
        Card::create(["color" => "white", "text" => "The American Dream"]);
        Card::create(["color" => "white", "text" => "The Amish."]);
        Card::create(["color" => "white", "text" => "The art of seduction."]);
        Card::create(["color" => "white", "text" => "The Big Bang."]);
        Card::create(["color" => "white", "text" => "The Blood of Christ."]);
        Card::create(["color" => "white", "text" => "The Boy Scouts of America."]);
        Card::create(["color" => "white", "text" => "The Care Bear Stare."]);
        Card::create(["color" => "white", "text" => "The Chinese gymnastics team."]);
        Card::create(["color" => "white", "text" => "The chronic."]);
        Card::create(["color" => "white", "text" => "The clitoris."]);
        Card::create(["color" => "white", "text" => "The cool, refreshing taste of Pepsi®."]);
        Card::create(["color" => "white", "text" => "The Dance of the Sugar Plum Fairy."]);
        Card::create(["color" => "white", "text" => "The deformed."]);
        Card::create(["color" => "white", "text" => "The Devil Himself."]);
        Card::create(["color" => "white", "text" => "The Donald Trump Seal of Approval.™"]);
        Card::create(["color" => "white", "text" => "The drama club."]);
        Card::create(["color" => "white", "text" => "The entire Mormon Tabernacle Choir."]);
        Card::create(["color" => "white", "text" => "The female orgasm."]);
        Card::create(["color" => "white", "text" => "The folly of man."]);
        Card::create(["color" => "white", "text" => "The forbidden fruit."]);
        Card::create(["color" => "white", "text" => "The Force."]);
        Card::create(["color" => "white", "text" => "The gays."]);
        Card::create(["color" => "white", "text" => "The glass ceiling."]);
        Card::create(["color" => "white", "text" => "The Great Depression."]);
        Card::create(["color" => "white", "text" => "The Hamburglar."]);
        Card::create(["color" => "white", "text" => "The hardworking Mexican."]);
        Card::create(["color" => "white", "text" => "The heart of a child."]);
        Card::create(["color" => "white", "text" => "The Holy Bible."]);
        Card::create(["color" => "white", "text" => "The homosexual agenda."]);
        Card::create(["color" => "white", "text" => "The homosexual lifestyle."]);
        Card::create(["color" => "white", "text" => "The Hustle."]);
        Card::create(["color" => "white", "text" => "The inevitable heat death of the universe."]);
        Card::create(["color" => "white", "text" => "The invisible hand."]);
        Card::create(["color" => "white", "text" => "The Jews."]);
        Card::create(["color" => "white", "text" => "The KKK"]);
        Card::create(["color" => "white", "text" => "The Kool-Aid Man."]);
        Card::create(["color" => "white", "text" => "The light of a billion suns."]);
        Card::create(["color" => "white", "text" => "The Little Engine That Could."]);
        Card::create(["color" => "white", "text" => "The Make-A-Wish® Foundation."]);
        Card::create(["color" => "white", "text" => "The milk man."]);
        Card::create(["color" => "white", "text" => "The miracle of childbirth."]);
        Card::create(["color" => "white", "text" => "The morbidly obese."]);
        Card::create(["color" => "white", "text" => "The Patriarchy."]);
        Card::create(["color" => "white", "text" => "The penny whistle solo from 'My Heart Will Go On'."]);
        Card::create(["color" => "white", "text" => "The People's Elbow."]);
        Card::create(["color" => "white", "text" => "The pirate's life."]);
        Card::create(["color" => "white", "text" => "The placenta."]);
        Card::create(["color" => "white", "text" => "The plot of a Michael Bay movie."]);
        Card::create(["color" => "white", "text" => "The Pope."]);
        Card::create(["color" => "white", "text" => "The profoundly handicapped."]);
        Card::create(["color" => "white", "text" => "The Rapture."]);
        Card::create(["color" => "white", "text" => "The Red Menace."]);
        Card::create(["color" => "white", "text" => "The Rev. Dr. Martin Luther King, Jr."]);
        Card::create(["color" => "white", "text" => "The rhythms of Africa."]);
        Card::create(["color" => "white", "text" => "The South."]);
        Card::create(["color" => "white", "text" => "The Superdome."]);
        Card::create(["color" => "white", "text" => "The taint; the grundle; the fleshy fun-bridge."]);
        Card::create(["color" => "white", "text" => "The Tempur-Pedic® Swedish Sleep System™."]);
        Card::create(["color" => "white", "text" => "The terrorists."]);
        Card::create(["color" => "white", "text" => "The Thong Song."]);
        Card::create(["color" => "white", "text" => "The Three-Fifths compromise."]);
        Card::create(["color" => "white", "text" => "The token minority."]);
        Card::create(["color" => "white", "text" => "The Trail of Tears"]);
        Card::create(["color" => "white", "text" => "The true meaning of Christmas."]);
        Card::create(["color" => "white", "text" => "The Übermensch."]);
        Card::create(["color" => "white", "text" => "The Underground Railroad."]);
        Card::create(["color" => "white", "text" => "The unstoppable tide of Islam."]);
        Card::create(["color" => "white", "text" => "The violation of our most basic human rights."]);
        Card::create(["color" => "white", "text" => "The Virginia Tech Massacre"]);
        Card::create(["color" => "white", "text" => "The wonders of the Orient."]);
        Card::create(["color" => "white", "text" => "The World of Warcraft."]);
        Card::create(["color" => "white", "text" => "The wrath of Vladimir Putin."]);
        Card::create(["color" => "white", "text" => "Third base."]);
        Card::create(["color" => "white", "text" => "This answer is postmodern."]);
        Card::create(["color" => "white", "text" => "This year's mass shooting."]);
        Card::create(["color" => "white", "text" => "Those times when you get sand in your vagina."]);
        Card::create(["color" => "white", "text" => "Three dicks at the same time."]);
        Card::create(["color" => "white", "text" => "Throwing a virgin into a volcano."]);
        Card::create(["color" => "white", "text" => "Tickle Me Elmo."]);
        Card::create(["color" => "white", "text" => "Tickling Sean Hannity, even after he tells you to stop."]);
        Card::create(["color" => "white", "text" => "Tiger Woods."]);
        Card::create(["color" => "white", "text" => "Tom Cruise."]);
        Card::create(["color" => "white", "text" => "Toni Morrison's vagina."]);
        Card::create(["color" => "white", "text" => "Too much hair gel."]);
        Card::create(["color" => "white", "text" => "Twinkies®."]);
        Card::create(["color" => "white", "text" => "Two midgets shitting into a bucket."]);
        Card::create(["color" => "white", "text" => "Unfathomable stupidity."]);
        Card::create(["color" => "white", "text" => "Uppercuts."]);
        Card::create(["color" => "white", "text" => "Used panties."]);
        Card::create(["color" => "white", "text" => "Vehicular homicide."]);
        Card::create(["color" => "white", "text" => "Vehicular manslaughter."]);
        Card::create(["color" => "white", "text" => "Viagra®."]);
        Card::create(["color" => "white", "text" => "Vigilante justice."]);
        Card::create(["color" => "white", "text" => "Vigorous jazz hands."]);
        Card::create(["color" => "white", "text" => "Vikings."]);
        Card::create(["color" => "white", "text" => "Waiting 'til marriage."]);
        Card::create(["color" => "white", "text" => "Waking up half-naked in a Denny's parking lot."]);
        Card::create(["color" => "white", "text" => "Waterboarding."]);
        Card::create(["color" => "white", "text" => "Wearing underwear inside-out to avoid doing laundry."]);
        Card::create(["color" => "white", "text" => "Wet dreams."]);
        Card::create(["color" => "white", "text" => "When you fart and a little bit comes out."]);
        Card::create(["color" => "white", "text" => "Whipping it out."]);
        Card::create(["color" => "white", "text" => "White people."]);
        Card::create(["color" => "white", "text" => "White privilege."]);
        Card::create(["color" => "white", "text" => "White-man scalps."]);
        Card::create(["color" => "white", "text" => "Wifely duties."]);
        Card::create(["color" => "white", "text" => "Will Smith."]);
        Card::create(["color" => "white", "text" => "William Shatner."]);
        Card::create(["color" => "white", "text" => "Winking at old people."]);
        Card::create(["color" => "white", "text" => "Wiping her butt."]);
        Card::create(["color" => "white", "text" => "Women in yogurt commercials."]);
        Card::create(["color" => "white", "text" => "Women's suffrage."]);
        Card::create(["color" => "white", "text" => "World peace."]);
        Card::create(["color" => "white", "text" => "Yeast."]);
        Card::create(["color" => "white", "text" => "YOU MUST CONSTRUCT ADDITIONAL PYLONS."]);
        Card::create(["color" => "white", "text" => "Your weird brother."]);
        Card::create(["text" => "	", "color" => "black"]);
        Card::create(["text" => "______: Good to the last drop.	", "color" => "black"]);
        Card::create(["text" => "______: kid-tested, mother-approved.	", "color" => "black"]);
        Card::create(["text" => "______? There's an app for that.	", "color" => "black"]);
        Card::create(["text" => "______. Betcha can't have just one!	", "color" => "black"]);
        Card::create(["text" => "______. High five, bro.	", "color" => "black"]);
        Card::create(["text" => "______. It's a trap!	", "color" => "black"]);
        Card::create(["text" => "______. That's how I want to die.	", "color" => "black"]);
        Card::create(["text" => "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.	", "color" => "black"]);
        Card::create(["text" => "A romantic, candlelit dinner would be incomplete without ______.	", "color" => "black"]);
        Card::create(["text" => "After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.	", "color" => "black"]);
        Card::create(["text" => "After the earthquake, Sean Penn brought ______ to the people of Haiti.	", "color" => "black"]);
        Card::create(["text" => "Alternative medicine is now embracing the curative powers of ______.	", "color" => "black"]);
        Card::create(["text" => "Anthropologists have recently discovered a primitive tribe that worships ______.	", "color" => "black"]);
        Card::create(["text" => "BILLY MAYS HERE FOR ______.	", "color" => "black"]);
        Card::create(["text" => "But before I kill you, Mr. Bond, I must show you ______.	", "color" => "black"]);
        Card::create(["text" => "Coming to Broadway this season, ______: The Musical.	", "color" => "black"]);
        Card::create(["text" => "Daddy, why is Mommy crying?	", "color" => "black"]);
        Card::create(["text" => "Dear Abby, I'm having some trouble with ______ and would like your advice.	", "color" => "black"]);
        Card::create(["text" => "Due to a PR fiasco, Walmart no longer offers ______.	", "color" => "black"]);
        Card::create(["text" => "During his childhood, Salvador Dali produced hundreds of paintings of ______.	", "color" => "black"]);
        Card::create(["text" => "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.	", "color" => "black"]);
        Card::create(["text" => "During sex, I like to think about ______.	", "color" => "black"]);
        Card::create(["text" => "Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.	", "color" => "black"]);
        Card::create(["text" => "Here is the church Here is the steeple Open the doors And there is ______.	", "color" => "black"]);
        Card::create(["text" => "How am I maintaining my relationship status?	", "color" => "black"]);
        Card::create(["text" => "How did I lose my virginity?	", "color" => "black"]);
        Card::create(["text" => "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.	", "color" => "black"]);
        Card::create(["text" => "I drink to forget ______.	", "color" => "black"]);
        Card::create(["text" => "I get by with a little help from ______.	", "color" => "black"]);
        Card::create(["text" => "I got 99 problems but ______ ain't one.	", "color" => "black"]);
        Card::create(["text" => "I wish I hadn't lost the instruction manual for ______.	", "color" => "black"]);
        Card::create(["text" => "I'm sorry, Professor, but I couldn't complete my homework because of ______.	", "color" => "black"]);
        Card::create(["text" => "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?	", "color" => "black"]);
        Card::create(["text" => "In 1,000 years, when paper money is but a distant memory, ______ will be our currency.	", "color" => "black"]);
        Card::create(["text" => "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.	", "color" => "black"]);
        Card::create(["text" => "In L.A. County Jail, word is you can trade 200 cigarettes for ______.	", "color" => "black"]);
        Card::create(["text" => "In Michael Jackson's final moments, he thought about ______.	", "color" => "black"]);
        Card::create(["text" => "In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.	", "color" => "black"]);
        Card::create(["text" => "Instead of coal, Santa now gives the bad children ______.	", "color" => "black"]);
        Card::create(["text" => "Introducing X-Treme Baseball! It's like baseball, but with ______!	", "color" => "black"]);
        Card::create(["text" => "It’s a pity that kids these days are all getting involved with ______	", "color" => "black"]);
        Card::create(["text" => "Life for American Indians was forever changed when the White Man introduced them to ______.	", "color" => "black"]);
        Card::create(["text" => "Life was difficult for cavemen before ______.	", "color" => "black"]);
        Card::create(["text" => "Major League Baseball has banned ______ for giving players an unfair advantage.	", "color" => "black"]);
        Card::create(["text" => "Maybe she's born with it. Maybe it's ______.	", "color" => "black"]);
        Card::create(["text" => "MTV's new reality show features eight washed-up celebrities living with ______.	", "color" => "black"]);
        Card::create(["text" => "Next from J.K. Rowling: Harry Potter and the Chamber of ______.	", "color" => "black"]);
        Card::create(["text" => "Next on ESPN2: the World Series of ______.	", "color" => "black"]);
        Card::create(["text" => "Sorry everyone, I just ______.	", "color" => "black"]);
        Card::create(["text" => "Studies show that lab rats navigate mazes 50% faster after being exposed to ______.	", "color" => "black"]);
        Card::create(["text" => "The class field trip was completely ruined by ______.	", "color" => "black"]);
        Card::create(["text" => "The new Chevy Tahoe. With the power and space to take ______ everywhere you go.	", "color" => "black"]);
        Card::create(["text" => "The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.	", "color" => "black"]);
        Card::create(["text" => "The U.S. has begun airdropping ______ to the children of Afghanistan.	", "color" => "black"]);
        Card::create(["text" => "They said we were crazy. They said we couldn't put ______ inside of ______. They were wrong.	", "color" => "black"]);
        Card::create(["text" => "This is the way the world ends, not with a bang but with ______	", "color" => "black"]);
        Card::create(["text" => "Today on Maury: 'Help! My son is ______!'", "color" => "black"]);
        Card::create(["text" => "TSA guidelines now prohibit ______ on airplanes	", "color" => "black"]);
        Card::create(["text" => "War! What is it good for?	", "color" => "black"]);
        Card::create(["text" => "What am I giving up for Lent?	", "color" => "black"]);
        Card::create(["text" => "What are my parents hiding from me?	", "color" => "black"]);
        Card::create(["text" => "What did I bring back from Mexico?	", "color" => "black"]);
        Card::create(["text" => "What did the U.S. airdrop to the children of Afghanistan?	", "color" => "black"]);
        Card::create(["text" => "What did Vin Diesel eat for dinner?	", "color" => "black"]);
        Card::create(["text" => "What do old people smell like?	", "color" => "black"]);
        Card::create(["text" => "What does Dick Cheney prefer?	", "color" => "black"]);
        Card::create(["text" => "What don't you want to find in your Chinese food?	", "color" => "black"]);
        Card::create(["text" => "What don't you want to find in your Kung Pao chicken?	", "color" => "black"]);
        Card::create(["text" => "What ended my last relationship?	", "color" => "black"]);
        Card::create(["text" => "What gets better with age?	", "color" => "black"]);
        Card::create(["text" => "What gives me uncontrollable gas?	", "color" => "black"]);
        Card::create(["text" => "What helps Obama unwind?	", "color" => "black"]);
        Card::create(["text" => "What is Batman's guilty pleasure?	", "color" => "black"]);
        Card::create(["text" => "What is George W. Bush thinking about right now?	", "color" => "black"]);
        Card::create(["text" => "What never fails to liven up the party?	", "color" => "black"]);
        Card::create(["text" => "What will always get you laid?	", "color" => "black"]);
        Card::create(["text" => "What will I bring back in time to convince people that I am a powerful wizard?	", "color" => "black"]);
        Card::create(["text" => "What would grandma find disturbing, yet oddly charming?	", "color" => "black"]);
        Card::create(["text" => "What's a girl's best friend?	", "color" => "black"]);
        Card::create(["text" => "What's my anti-drug?	", "color" => "black"]);
        Card::create(["text" => "What's my secret power?	", "color" => "black"]);
        Card::create(["text" => "What's Teach for America using to inspire inner city students to succeed?	", "color" => "black"]);
        Card::create(["text" => "What's that smell?	", "color" => "black"]);
        Card::create(["text" => "What's that sound?	", "color" => "black"]);
        Card::create(["text" => "What's the crustiest?	", "color" => "black"]);
        Card::create(["text" => "What's the most emo?	", "color" => "black"]);
        Card::create(["text" => "What's the new fad diet?	", "color" => "black"]);
        Card::create(["text" => "What's the next Happy Meal toy?	", "color" => "black"]);
        Card::create(["text" => "What's the next superhero?	", "color" => "black"]);
        Card::create(["text" => "What's there a ton of in heaven?	", "color" => "black"]);
        Card::create(["text" => "When I am a billionare, I shall erect a 50-foot statue to commemorate ______.	", "color" => "black"]);
        Card::create(["text" => "When I am President of the United States, I will create the Department of ______.	", "color" => "black"]);
        Card::create(["text" => "When I'm in prison, I'll have ______ smuggled in.	", "color" => "black"]);
        Card::create(["text" => "When Pharaoh remained unmoved, Moses called down a Plague of ______.	", "color" => "black"]);
        Card::create(["text" => "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____", "color" => "black"]);
        Card::create(["text" => "White people like ______.	", "color" => "black"]);
        Card::create(["text" => "Who stole the cookies from the cookie jar?	", "color" => "black"]);
        Card::create(["text" => "Why am I sticky?	", "color" => "black"]);
        Card::create(["text" => "Why can't I sleep at night?	", "color" => "black"]);
        Card::create(["text" => "Why do I hurt all over?	", "color" => "black"]);
        Card::create(["text" => "When I'm in prison, I'll have ______ smuggled in.	", "color" => "black"]);
        Card::create(["text" => "Who stole the cookies from the cookie jar?	", "color" => "black"]);
    }
}
